services:
  traefik:
    image: "traefik:v3.3"
    command:
      - "--api.dashboard=true"
      - "--accesslog.format=json"
      - "--log.level=INFO"
      # - "--log.level=DEBUG"
      
      - "--providers.swarm=true"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"

      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.websecure.http3=true"
      - "--entryPoints.websecure.http3.advertisedPort=443"
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=15m"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=15m"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=15m"
      - "--entryPoints.web.transport.respondingTimeouts.writeTimeout=15m"

      - "--entrypoints.web-internal.address=:8080"
      - "--entryPoints.web-internal.transport.respondingTimeouts.readTimeout=15m"
      - "--entryPoints.web-internal.transport.respondingTimeouts.writeTimeout=15m"

      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=karpov.kir.v@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    # https://community.traefik.io/t/traefik-running-on-docker-swarm-x-real-ip-and-x-forward-for-are-incorrect/26074/2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro"
      - "./auth/basic-auth.password:/etc/traefik/basic-auth.password"
      - "traefik-certificates-data:/letsencrypt"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true

volumes:
  traefik-certificates-data:
