services:
  web:
    image: dr.kk-forge.com/guessir-web
    networks:
      - traefik_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.guessir-web.rule=Host(`guessir.kk-forge.com`)"
        - "traefik.http.services.guessir-web.loadbalancer.server.port=80"
        - "traefik.http.routers.guessir-web.entrypoints=websecure"
        - "traefik.http.routers.guessir-web.tls.certresolver=letsencrypt"
  backend:
    image: dr.kk-forge.com/guessir-backend
    networks:
      - traefik_network
    environment:
      DB: "true"
      DB_NAME: "guessir"
      DB_USER: "admin"
      DB_PW: "password"
      DB_HOST: "guessir_db"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.guessir-backend.rule=Host(`guessir-api.kk-forge.com`)"
        - "traefik.http.services.guessir-backend.loadbalancer.server.port=3020"
        - "traefik.http.routers.guessir-backend.entrypoints=websecure"
        - "traefik.http.routers.guessir-backend.tls.certresolver=letsencrypt"
    depends_on:
      - db

  db:
    image: postgres:15
    networks:
      - traefik_network
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "guessir"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d guessir"]
      interval: 1s

networks:
  traefik_network:
    external: true

volumes:
  db-data:
